#!/bin/bash
declare -A PORT_NICKNAMES
PORT_NICKNAMES["analog-output-lineout"]="Speakers"
PORT_NICKNAMES["analog-output-headphones"]="Headphones"
SINK_ICON=" "

function getPortNickname(){
        portNickname="${PORT_NICKNAMES[$1]}"
}

function getCurPort() {
        if ! pulseaudio --check; then return 1; fi
        curPort=$(pactl list sinks | grep 'Active Port' | cut -d ' ' -f 3)
}

getCurPort
echo $curPort

getPortNickname $curPort

echo $portNickname

if ["$portNickname" = "Speakers"]; then
        echo $portNickname
        SINK_ICON="蓼 "
    fi

echo $SINK_ICON
